apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-mzvs-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:1cd155cdd4beef6de1f077467573c58b7a75e0448beb4d25c548c1b68e2a9d24
        name: container-image
        resources: {}
status: {}
